# Generated by Django 4.2 on 2023-07-28 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolioapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='aboutmyself',
            name='name',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
