# Generated by Django 4.2 on 2023-07-28 14:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolioapp', '0002_aboutmyself_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='aboutmyself',
            old_name='name',
            new_name='title',
        ),
    ]
