# Generated by Django 4.2 on 2023-07-28 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolioapp', '0003_rename_name_aboutmyself_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='schoolexperience',
            name='is_school',
            field=models.BooleanField(default=True),
        ),
    ]
