# Generated by Django 4.2 on 2023-07-28 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolioapp', '0004_schoolexperience_is_school'),
    ]

    operations = [
        migrations.AddField(
            model_name='projects',
            name='link',
            field=models.URLField(blank=True, null=True),
        ),
    ]
